osx_image: xcode10.2
language: swift
os: osx
xcode_project: RealmSwiftTutorial.xcodeproj
xcode_workspace: RealmSwiftTutorial.xcworkspace
xcode_scheme: RealmSwiftTutorial
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8